version: '3'
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-12-13T22-19-12Z
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=minio_password
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: server --console-address ":9001" /data # command to run in standalone mode

volumes:
  minio_data:
    driver: local